parameters:
  sites_demo13_nopCommerce02_name:
    value: "{{ site_name }}"
  serverfarms_demo13_nopCommerce02_3a9f_name:
    value: "{{ server_farm_name }}"
  metricAlerts_DXC_Warning_WebApp_demo13_nopCommerce02_Requests_name:
    value: "{{ warning_metric_alert_name }}"
  metricAlerts_DXC_Critical_WebApp_demo13_nopCommerce02_Requests_name:
    value: "{{ critical_metric_alert_name }}"
  location:
    value: "{{ location }}"