---
# tasks file for ansible-aks-arm-provision

- include_vars: "../vars/{{ deployment_type }}.yml"

- name: "Create Azure Deploy"
  azure_rm_deployment:
    resource_group: "{{ resource_group }}"
    client_id: "{{ client_id }}"
    secret: "{{ client_secret }}"
    tenant: "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
    name: "{{ deployment_name }}"
    location: "{{ location }}"
    parameters: "{{ parameters }}"
    template: "{{ lookup( 'file' , '../files/deployment_type.json')}}"
  register: azure

- name: "Task Result: Create Azure Deploy"
  debug:
      msg: "{{ azure }}"