---
# tasks file for ansible-aks-arm-provision

- name: "Create Azure Deploy"
  azure_rm_deployment:
    resource_group: "{{ resource_group }}"
    client_id: "{{ client_id }}"
    secret: "{{ client_secret }}"
    tenant: "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
    name: "{{ deployment_name }}"
    location: "{{ location }}"
    parameters:
      sites_demo13_nopCommerce02_name:
        value: "{{ site_name }}"
      serverfarms_demo13_nopCommerce02_3a9f_name:
        value: "{{ server_farm_name }}"
      metricAlerts_DXC_Warning_WebApp_demo13_nopCommerce02_Requests_name:
        value: "{{ warning_metric_alert_name }}"
      metricAlerts_DXC_Critical_WebApp_demo13_nopCommerce02_Requests_name:
        value: "{{ critical_metric_alert_name }}"
      location:
        value: "{{ location }}"
    template: "{{ lookup( 'file' , '../files/app_service.json')}}"
  register: azure

- name: "Task Result: Create Azure Deploy"
  debug:
      msg: "{{ azure }}"