---
# tasks file for ansible-aks-provision

- debug:
    msg: "Client ID: {{ client_id }}, Client Key: {{ client_secret }}"

- set_fact:
    parameters:
      managedClusters_Demo_AKS_name:
        value: "{{ aks_name }}"
      environment:
        value: "{{ environment }}"
      vmSize:
        value: "{{ vm_size }}"
      kubernetesVersion:
        value: "{{ aks_version }}"
      clientId:
        value: "{{ client_id }}"
      resource_group:
        value: "{{ resource_group }}"
      node_count:
        value: "{{ node_count }}"
      location:
        value: "{{ location }}"

- debug:
    msg: "{{ parameters }}"

- name: "Create Azure Deploy"
  azure_rm_deployment:
    resource_group: "{{ resource_group }}"
    client_id: "{{ client_id }}"
    secret: "{{ client_secret }}"
    tenant: "{{ tenant_id }}"
    subscription_id: "{{ subscription_id }}"
    name: "{{ deployment_name }}"
    location: "{{ location }}"
    parameters: "{{ parameters }}"
    template: "{{ lookup( 'file' , '../files/aks.json')}}"
  register: azure

- name: "Task Result: Create Azure Deploy"
  debug:
      msg: "{{ azure }}"  

# - name: "Create Azure Deploy"
#   azure_rm_deployment:
#     resource_group: "{{ resource_group }}"
#     client_id: "{{ client_id }}"
#     secret: "{{ client_secret }}"
#     tenant: "{{ tenant_id }}"
#     subscription_id: "{{ subscription_id }}"
#     name: "{{ deployment_name }}"
#     location: "{{ location }}"
#     parameters:
#       managedClusters_Demo_AKS_name:
#         value: "{{ aks_name }}"
#       environment:
#         value: "{{ environment }}"
#       vmSize:
#         value: "{{ vm_size }}"
#       kubernetesVersion:
#         value: "{{ aks_version }}"
#       clientId:
#         value: "{{ client_id }}"
#       resource_group:
#         value: "{{ resource_group }}"
#       node_count:
#         value: "{{ node_count }}"
#       location:
#         value: "{{ location }}"
#     template: "{{ lookup( 'file' , '../files/aks.json')}}"
#   register: azure

# - name: "Task Result: Create Azure Deploy"
#   debug:
#       msg: "{{ azure }}"