---

- name: "Delete CloudForms Service"
  uri:
    url: "https://{{ rhcf_host }}/api/services/{{ service_id }}"
    method: DELETE
    body_format: json
    body:
      action: delete
    user: "{{ rhcf_user }}"
    password: "{{ rhcf_pass }}"
    validate_certs: no
    force_basic_auth: yes
    status_code: 200
  register: rhcf_service_delete
  ignore_errors: True

- name: "Task Result: Delete CloudForms Service"
  debug: 
    msg: rhcf_service_delete