---
# tasks file for ansible-aks-scale

- name: Scaling an existed AKS cluster
  azure_rm_aks:
    name: "{{ aks_name }}"
    location: "{{ location }}"
    resource_group: "{{ resource_group }}"
    dns_prefix: "{{ aks_name }}"
    linux_profile:
      admin_username: "{{ username }}"
      ssh_key: "{{ ssh_key }}"
    service_principal:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
    agent_pool_profiles:
      - name: default
        count: 3
        vm_size: Standard_D2_v2